## You should change each of the following fields
## to customize your blog

title: Brylee's Big-Brain Blog
description: "Not the average data science blog. The place to find detailed answers made simple to all your data science questions." 
author: Brylee Wilcox
author_description: "Statistical science student at BYU with a passion for learning and sharing experiences with others." 

url: https://wilcobry.github.io ## change this to https://yourusername.github.io
baseurl: /blog ## change this to the name of your blog repository
header_image: /github_image.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github: @wilcobry
    facebook: @wilcobry
    email: wilcobry@gmail.com
    linkedin: Brylee Wilcox



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




